name: Security Scan

on:
  push:
    branches: [ "main", "security" ]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  mobfscan:
    uses: gastonbarbaccia/devsecops_template/.github/workflows/mobfscan.yml@main